version: "3"

services:
  web:
    build: ./.docker/php
    volumes:
      - ./src:/var/www
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres

  nginx:
    build: ./.docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    volumes:
      - ./.docker/pgadmin4_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres

volumes:
  pgadmindata:
